### ISSUE TITLE
Add a header and footer

### ISSUE THREAD

**Issue by tylervz** [jglamine/calvinwebprint#16]
We should have a consistent footer at the bottom of the page, and a consistent header at the top of the page. 

The header and footer should have links to things like settings (once #2 is resolved), [github](https://github.com/jglamine/calvinwebprint), stats (once #9 is resolved), help, and an about page.

The settings link should be a [font-awesome gear](http://fontawesome.io/icon/cog/), and the link should only appear when a user is logged in.

It should be laid out as follows:
Header: Calvin web print | help | settings 
Footer: about | stats | fork me on github

Headers and footers can be done through a jinja template in flask. Right now the main page is being served as a static file, and the black header bar at the top of the page is rendered using javascript. This should be replaced with a route in flask which renders a template. Templates can be nested, so they can all be surrounded by the header and the footer.

For an example, see here, where the template "extends" the base.html template: https://github.com/jglamine/phage/blob/master/webphamerator/app/templates/database.html

**Comment by jglamine** [comment]
We should also have a consistent header. Right now the black header bar at the top of the page is rendered using javascript, but that should be moved into the base jinja template as well.

Some of the links should be in the header, others should be in the footer. Here's what I'm thinking:

Header: Calvin web print | settings | stats | about
Footer: fork me on github

Settings should only show up if a user is signed in.

**Comment by tylervz** [comment]
I was thinking we should use a gear icon for settings, in which case would look best on the farthest right of the header.

I don't like the idea of putting stats and about in the header because I don't think they are important enough. We don't want to distract users with links they don't click on often. If a user is really interested in our site, they will most likely scroll all the way to the bottom. Granted, I am envisioning the experience of a first time user looking our site.

I also don't think we should get rid of the help page because we have some worthwhile information there, and help & about seem to different purposes, at least the way I am imagining them. Help is for users wanting to know how to use the site. About is for users wanting to know why the site exists and who made it.

Header: Calvin web print | help | settings 
Footer: about | stats | fork me on github

**Comment by jglamine** [comment]
Sounds good. Let's go with that.

As for the gear icon, do we use icons elsewhere in the site? If so, we
should consider bringing in font awesome: http://fontawesome.io/, and being
consistent about using that in the site. This way adding additional icons
will be easy and they will all look consistent.

**Comment by tylervz** [comment]
I don't think we do, but I still like the idea of adding fontawesome.
We could add this http://fontawesome.io/icon/github-square/ to sit beside our link to github.
And I'm sure we could add this http://fontawesome.io/icon/print/ somewhere and have it look nice.

**Comment by tylervz** [comment]
Or http://fontawesome.io/icon/code-fork/

**Comment by tylervz** [comment]
Oh, and we could potentially use fontawesome for our spinners. http://fontawesome.io/examples/#animated

**Comment by jglamine** [comment]
Yes, let's do that. This solves a lot of problems.
