### ISSUE TITLE
Search engine optimization: add meta tags for title and description.

### ISSUE THREAD

**Issue by jglamine** [jglamine/calvinwebprint#21]
In google searches, the description of our site is terrible. Fix this by adding meta tags for title and description.

See this search for what it looks like now (we're about 4 results down):
https://www.google.com/webhp?sourceid=chrome-instant&rlz=1C1CHFX_enUS461US461&ion=1&espv=2&ie=UTF-8#q=calvin%20web%20print

Be sure to include the words `calvin` and `uniFlow` in the description, as that is what students might search for.

**Comment by yjftsjthsd-g** [comment]
Dibs.
-Brian Cole

**Comment by tylervz** [comment]
Fixed in PR: #35
