### ISSUE TITLE
Preselect the correct google account when adding the uniflow printer

### ISSUE THREAD

**Issue by jglamine** [jglamine/calvinwebprint#31]
Google's `add public printer` endpoint doesn't let us choose which user to add the printer to.

If you're signed into multiple google accounts, it just uses the first one.

But, there's a workaround. Replace the link to `calvin.edu/go/cloudprint` with a link to the google account chooser page, with the email address already filled in and the redirect URL set to the add public printer page. We have to use the google address for the redirect URL instead of `calvin.edu/go/cloudprint` because Google won't let us redirect to other domains.

```
https://accounts.google.com/AddSession?continue=https%3A%2F%2Fwww.google.com%2Fcloudprint%2Faddpublicprinter.html%3Fprinterid%3Deeec5cdd-8deb-e24a-8f04-30bf0447b555%26key%3D1187699760&service=cloudprint&sacu=1&acui=2#Email=jgl5%40students.calvin.edu
```

replace the Email= parameter with the actual email we want the person to use

**Comment by jglamine** [comment]
@tylervz , is this brilliant or what?

**Comment by tylervz** [comment]
Pretty smart! We still need to handle @calvin.edu accounts appropriately,
but this will get taken care in issue #3.

**Comment by jglamine** [comment]
Would this redirect url work with @calvin.edu accounts? Do they still have
associated Google accounts?

**Comment by tylervz** [comment]
That's a good question. I'll send Michael from CIT an email.

**Comment by jglamine** [comment]
We could also ask a professor to help us test it.

**Comment by tylervz** [comment]
That could work too.

**Comment by twodarek** [comment]
@calvin.edu accounts are registered with the @calvin.edu Google Apps domain, so the Google OAuth will work for staff/faculty.
